name: Enhanced Notify Telegram on Proxy Update

on:
  push:
    paths:
      - 'https.txt'  # Triggers only when https.txt changes

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Calculate proxy metrics
        id: metrics
        run: |
          echo "TOTAL_PROXIES=$(wc -l < https.txt)" >> $GITHUB_ENV
          echo "FETCH_TIME=$(($SECONDS - START_TIME))" >> $GITHUB_ENV
          PING_TIME=$(ping -c 4 example.com | tail -1| awk -F '/' '{print $5}')
          echo "AVERAGE_PING=$PING_TIME" >> $GITHUB_ENV

      - name: Send update notification to Telegram
        run: node sendNotification.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: '@FreshProxyLists'  # Or use -1002161984488 for a group ID
          FETCH_TIME: ${{ env.FETCH_TIME }}
          TOTAL_PROXIES: ${{ env.TOTAL_PROXIES }}
          AVERAGE_PING: ${{ env.AVERAGE_PING }}
