name: Continuous Proxy Checking

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch_and_check_proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Download Proxy Lists
      run: |
        curl https://raw.githubusercontent.com/zloi-user/hideip.me/main/https.txt > https.txt
        curl https://raw.githubusercontent.com/themiralay/Proxy-List-World/master/data.txt > additional_proxies.txt

    - name: Check a sample proxy
      run: |
        proxy=$(head -n 1 https.txt)
        echo "Testing $proxy"
        curl --proxy-insecure -k --proxy "$proxy" -o - https://api.my-ip.io/ip

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add https.txt additional_proxies.txt
        git commit -m "Update proxy lists" || echo "No changes to commit"
        git push
