name: Update Proxy Lists Frequently

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minute (GitHub Actions doesn't support less than 1-minute intervals)
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-proxy-lists:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml pysocks

    - name: Debug PROXY_SOURCES
      run: |
        echo "PROXY_SOURCES length: ${#PROXY_SOURCES}"
        echo "PROXY_SOURCES first 10 characters: ${PROXY_SOURCES:0,10}..."

    - name: Process and Check Proxies
      run: |
        # Python script to download, process, and check proxies

    - name: Commit and Push Changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *.txt proxy_stats.json
        git commit -m "Update proxy lists [skip ci]" -a || echo "No changes to commit"
        git push
