name: Continuous Proxy Checking

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest requests
        
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Download Proxy Lists
      run: |
        curl https://raw.githubusercontent.com/zloi-user/hideip.me/main/http.txt -o http.txt
        curl https://raw.githubusercontent.com/zloi-user/hideip.me/main/https.txt -o https.txt
        curl https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks4.txt -o socks4.txt
        curl https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks5.txt -o socks5.txt
        curl https://raw.githubusercontent.com/zloi-user/hideip.me/main/connect.txt -o connect.txt
        curl https://raw.githubusercontent.com/themiralay/Proxy-List-World/master/data.txt -o data.txt
        curl https://raw.githubusercontent.com/themiralay/Proxy-List-World/master/data-with-geolocation.json -o geolocation.json
        curl https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks4.txt -o socks4.txt
        curl https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks5.txt -o socks5.txt
        curl https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/http.txt -o http.txt
        curl https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/https.txt -o https.txt

    - name: Commit and Push Changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'likhonsheikhbd'
        git config --global user.email 'likhonsheikhbd@outlook.com'
        git add http.txt https.txt socks4.txt socks5.txt connect.txt data.txt geolocation.json
        git commit -m "Update proxy lists" -a || echo "No changes to commit"
        git -c http.extraHeader="AUTHORIZATION: bearer ${{ secrets.GH_PAT }}" push
