name: Continuous Proxy Checking

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest requests

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Download and Combine Proxy Lists
        run: |
          curl https://raw.githubusercontent.com/zloi-user/hideip.me/main/http.txt >> http.txt
          curl https://raw.githubusercontent.com/zloi-user/hideip.me/main/https.txt >> https.txt
          curl https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks4.txt >> socks4.txt
          curl https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks5.txt >> socks5.txt
          curl https://raw.githubusercontent.com/themiralay/Proxy-List-World/master/data.txt >> data.txt
          curl https://raw.githubusercontent.com/themiralay/Proxy-List-World/master/data-with-geolocation.json >> geolocation.json
          curl https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks4.txt >> socks4.txt
          curl https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks5.txt >> socks5.txt
          curl https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/http.txt >> http.txt
          curl https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/https.txt >> https.txt
          
          # Remove duplicates and clean each file
          for file in *.txt *.json; do
            sort -u $file -o $file
          done

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'likhonsheikhbd'
          git config --global user.email 'likhonsheikhbd@outlook.com'
          git add *.txt *.json
          git commit -m "Update proxy lists" -a || echo "No changes to commit"
          git -c http.extraHeader="AUTHORIZATION: bearer ${{ secrets.GH_PAT }}" push
